version: '3.4'

x-app-service-template: &app
  build: rails_app
  image: yabeda-rails-app:1.0
  volumes:
    - ./rails_app:/app

services:
  rails:
    <<: *app
    ports:
      - 5000:5000
    environment:
      REDIS_URL: redis://redis:6379/0
    stdin_open: true
    tty: true
    depends_on:
      - redis

    command: bundle exec puma -C config/puma.rb

  sidekiq:
    <<: *app
    ports:
      - 5100:5100
    environment:
      PORT: 5100
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis

    command: sidekiq -C config/sidekiq.yml

  redis:
    image: redis
    command: redis-server
    
  solr:
    image: solr:8
    ports:
      - "8983:8983"
    volumes:
      - data:/var/solr
    command:
      - solr-precreate
      - gettingstarted
      
  solr-exporter:
    image: solr:8
    depends_on:
      - solr
    ports:
      - "9854:9854"
    entrypoint:
      - "/opt/solr-8.5.0/contrib/prometheus-exporter/bin/solr-exporter"
      - "-p"
      - "9854"
      - "-b"
      - "http://solr:8983/solr"
      - "-f"
      - "/opt/solr-8.5.0/contrib/prometheus-exporter/conf/solr-exporter-config.xml"
      - "-n"
      - "8"
    volumes:
      - ./dockerInfo/solr-exporter-config.xml:/opt/solr-8.5.0/contrib/prometheus-exporter/conf/solr-exporter-config.xml

  grafana:
    image: grafana/grafana:5.2.4
    depends_on:
      - prometheus    
    ports:
      - 3000:3000/tcp
    volumes: 
      - ./grafana_db:/var/lib/grafana
      - ./dockerInfo/prometheus.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      - ./dockerInfo/solr.yml:/etc/grafana/provisioning/dashboards/solr.yml
      - ./dockerInfo/grafana-solr-dashboard.json:/var/lib/grafana/dashboards/grafana-solr-dashboard.json
    user: "104"

  prometheus:
    image: prom/prometheus:v2.4.3
    volumes:
      - ./dockerInfo/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090/tcp
    depends_on:
      - rails

    command:
      - --config.file=/etc/prometheus/prometheus.yml

  rails_stressor:
    build: rails_stressor
    image: rails_stressor
    depends_on:
      - rails
    command: -z 2m -c 15 -m GET http://rails:5000
          
volumes:
  data: 
